### PR TITLE
Added support and instructions for installation on Safari

### PR DESCRIPTION
**Pull request by PolarWolf314**

### CODE REVIEW

**Review by JamesNZL — CHANGES_REQUESTED** [review]
Legend! :sparkles:

Looks really good, but can I ask a couple things:
1. In the interest of maintaining a consistent folder structure, is it possible to `mv notion-assignment-import-safari releases/safari`?
2. Just to reduce the diff size, could you please only stage actual changes in `README.md`, and not formatting changes? 😅

PS
```md
    <a href="#macos-instructions">
       <img src="https://img.shields.io/badge/Download_for-Safari-000000?style=for-the-badge&logo=safari&logoColor=FFFFFF" alt="Download for Safari">
    </a>
```

**Comment by PolarWolf314** [comment]
I have added the changes you requested. Sorry about the changes in `README.md`, I'm not experienced enough with git to know how to do that :(

**Comment by JamesNZL** [comment]
> I have added the changes you requested.
Thank you :crown:

> I'm not experienced enough with git to know how to do that :(
All good! I'll open a PR in your fork 😄

**Review by JamesNZL — APPROVED** [review]
✨

**Pull request merged**
